### ISSUE TITLE
Provision an IP address to provide to GCSS-MC

### ISSUE THREAD

**Issue by vcastro-DDS** [deptofdefense/solo#10]
- Obtain an IP address

Provision an IP address. GCSS-MC needs this IP address to add to their server in order to allow API calls to their SDE infrastructure.

**Comment by SCasarottoDDS** [comment]
From Nhi Lo:

> 
> Jeff,
> 1. I will need your IP(S) from your server
> 2. and a DoD Cert.
> 3. Also you should set up the URL on your side as well, for these are Web
> Services initiation, it will help to trace issue when you start using the eXML
> portion (even with an empty package).
> 
> If you are 'Nat-ing, please lets us know as well.
> 
> Roger will work with Stuart to provide you our end points.
> Remember, with STRATIS - majority of the data initiation is from STRATIS.
> 
> Will need 5 Working Day on my end (or earlier depends on our resource's
> workload).
> 
> 4. Once we pass the connection 'ping' test,  your functional team need to
> provide me with the DoDAAD (we will provide you spreadsheet to fill out) you
> plan to use so we can do proper setup.
> 

Is this enough info to move forward?

**Comment by vcastro-DDS** [comment]
We have allocated EIP addresses within AWS console and have sent the IP-hostname tuple to the GCSS-MC program office.
