### ISSUE TITLE
Maintain Supply House Informtion (Do we need)?

### ISSUE THREAD

**Issue by coachjeff** [deptofdefense/solo#108]
**Is your feature request related to a problem? Please describe.**
As a system administrator, I need to limit users to only view and process transactions for specific supply houses.

**Describe the solution you'd like**
A user can process transactions for one or more specific supply warehouses

**Additional context**
I am not sure if we have to maintain a list of supply houses or it can be imported from GCSS-MC

**Comment by vcastro-DDS** [comment]
We have issues in progress that split this issue up.
