### ISSUE TITLE
Decide on style guide

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#12]
## Research
See Jeff's comments 

## Recommendation 
See Jeff's comments 

## Action
Adopt [Black](https://github.com/psf/black) for linting and fixing Python code style
Adopt [Prettier](https://prettier.io/) for linting and fixing js/ts code style

## Screenshots
_Attach relevant screenshots here._

**Comment by jhackshaw-dds** [comment]
### Research 

#### python
 - [Python Enhancement Proposal 8](https://www.python.org/dev/peps/pep-0008/) is the official style guide for python code
 - [Black](https://github.com/psf/black) does code formatting and enforcement
 - Using black allows for style and syntax checks, as well as type checking via mypy

#### js/ts
 - [prettier](https://github.com/prettier/prettier) can lint and autofix js/ts code
 - eslint has plugins for typescript and prettier
 - Using eslint with prettier and typescript allows for style, type, and syntax checks

### Recommendation 
 - Adopt black for linting and fixing python code style
 - Adopt prettier for linting and fixing js/ts code style

### Action
N/A

**Comment by dds-hansolo** [comment]
Linters chosen and implemented in CI/CD pipeline:
Django: Black
React: Prettier
