### ISSUE TITLE
Decide on CI/CD pipeline tool

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#13]
### Research 
Github actions
Travisci
Jenkins
Circleci

### Action

**Comment by dds-hansolo** [comment]
After speaking with Jordan, it sounds that CircleCI is the best option as it is well tested, fed ramped, and DDS is familiar with it. I have explored both circleci and GitHub actions. Both are relatively easy to use and have a lot of nice features. At this point, I think CircleCI is the way to go.
