### ISSUE TITLE
Build Proprietary Compression Service and Local Build

### ISSUE THREAD

**Issue by dds-hansolo** [deptofdefense/solo#147]
**Is your feature request related to a problem? Please describe.**
As a developer, I would like to be able to send data to GCSS in a format they can accept.

**Describe the solution you'd like**
GCSS has indicated we must use agiledeltas proprietary compression software to compress/decompress the data. I would like a web service that can invoke either a compress or decompress request from the worker queue, and a way to run this locally without putting proprietary software on GitHub.

**Describe alternatives you've considered**
A CLI would be another option, but the worker would need the JRE installed, and we would be limited to how many instances we can spin up due to licensing.

**Additional context**
N/A.

**Comment by jhackshaw-dds** [comment]
via #148
