### ISSUE TITLE
Decide on container registry

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#15]
## Research
Look at DI2E 

1. Red hat Quay
-TLS Encryption Support
-Automatically conducts security scans on container images

## Recommendation 
_Provide a recommendation based upon the research._

## Action
_Describe the action taken._

## Screenshots
_Attach relevant screenshots here._

**Comment by jhackshaw-dds** [comment]
Mon Cala team decided on ECR.
