### ISSUE TITLE
Decide on security / dependency scanning 

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#16]
### Research 
snyk

### Action

**Comment by dds-hansolo** [comment]
I have investigated Snyk, and think it is an excellent option for our project. It can be integrated pretty easily with CircleCI, and can provide both dependency scanning and container security.

Other investigated options:

Gemnasium is a commercial tool with free starting plans. Gemnasium has its own database that draws from several sources. However, though the vulnerabilities are reviewed manually on a daily basis, advisories are not automatically published.

Hakiri is a commercial tool that offers dependency checking for Ruby and Rails-based GitHub projects using static code analysis. It offers free plans for public open-source projects and paid plans for private projects. It uses NVD and the Ruby Advisory Database.
