### ISSUE TITLE
Paginate status page table

### ISSUE THREAD

**Issue by jhackshaw-dds** [deptofdefense/solo#188]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to page through the table of documents in the status page.

**Describe the solution you'd like**
A generic Pagination component if one does not exist, and the ability to page through results in the status page using the Pagination component. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lit-dds** [comment]
Here is how the endpoint might look like: `/api/document/?page=2`
