### ISSUE TITLE
Backend - Django - View - Document list for the status page

### ISSUE THREAD

**Issue by lit-dds** [deptofdefense/solo#191]
Is your feature request related to a problem? Please describe.
As a developer, I want to be able to create an authenticated api endpoint so the frontend can utilize the json object correctly for the status page.

Depends on #160 and the rest of the models

Describe the solution you'd like
Create an authenticated document view and tests for get and post.

Describe alternatives you've considered
N/A

Additional context

**Comment by jhackshaw-dds** [comment]
via #227
