### ISSUE TITLE
Create Hello World Back-end Django App

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#20]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Include linting and and at least one test.

**Describe alternatives you've considered**
The Mon Cala team considered Node, Django and Spring because of the proprietary eXML converter written in Java.

**Additional context**
n/a

**Comment by dds-hansolo** [comment]
Hello world Django backend has been completed.
