### ISSUE TITLE
Security alert for development dependencies acorn and minimist via eslint

### ISSUE THREAD

**Issue by jhackshaw-dds** [deptofdefense/solo#210]
Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.
## Checklist
I have…
- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
~~[ ] attached screenshots illustrating relevant behavior.~~

## Expected Behavior
N/A

## Observed Behavior
Github has identified acorn and minimist as outdated dependencies that were installed due to eslint. The dependencies are only used in linting for development and CI.

## Steps to Reproduce
To reproduce this issue…
N/A

## Screenshots
N/A

**Comment by vcastro-DDS** [comment]
Minimist appears to be a dependency of eslint, fsevents, and other packages which have been flagged as a vulnerability. We will attempt to bump the version one some of the updates are pushed in those packages. Refer to the following GitHub issue:
https://github.com/eslint/eslint/issues/13050
