### ISSUE TITLE
Determine which database format to use for initial deployment, if any.

### ISSUE THREAD

**Issue by vcastro-DDS** [deptofdefense/solo#23]
## Research
_Provide The research into the topic._

## Recommendation 
_Provide a recommendation based upon the research._

## Action
_Describe the action taken._

## Screenshots
_Attach relevant screenshots here._

**Comment by lit-dds** [comment]
## Research
https://docs.djangoproject.com/en/3.0/ref/databases/

## Recommendation 
- Utilize sqlite to get the initial simplistic "hello world" up so everyone can reach the IP address for the development (placeholder). Once we find out what and how the schema of the database is, we then can switch it out with PostgreSQL database. Also, should not be utilized in production.
- Sqlite version (whatever comes with Django 3)
- PostgreSQL version 12

## Action
- Utilize Sqlite upfront and then transition to PostgreSQL
## Screenshots
- N/A

**Comment by lit-dds** [comment]
Initial format with sqlite is complete.

**Comment by scottpiercewDDS** [comment]
Use Django Sqlite for initial setup, then move to PostgeSQL.
