### ISSUE TITLE
Figure out how to interpret SOAP msg from GCSS-MC 

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#25]
## Research
The Interface Design document I 142 is a starting place.

Depends on #10 #11 #58 

## Recommendation 
N/A

## Action
N/A

## Screenshots
N/A

**Comment by vcastro-DDS** [comment]
Work has been conducted to interpret the messages. This is addressed now in Issue's that specifically require pulling and sending data to GCSS-MC.
