### ISSUE TITLE
Show error when attempting to enter non-existent SDN and provide a way to remove entry

### ISSUE THREAD

**Issue by vcastro-DDS** [deptofdefense/solo#253]
**Is your feature request related to a problem? Please describe.**
As a user, I want to know whether my SDN entry is valid and delete the entry whether or not it is valid. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jhackshaw-dds** [comment]
Duplicate issue opened #262
