### ISSUE TITLE
sqlite3 for unit tests prevents Faker from generating received_by column

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#298]
Thanks for submitting an issue! Below are a few things you can do to help us more quickly address the issue.
## Checklist
I have…
- [x] described in detail below both the behavior I expected and the behavior I observed.
- [x] thoroughly outlined below the steps to reproduce this issue, including relevant technical details (e.g. device, operating system, browser, browser version).
- [x] attached screenshots illustrating relevant behavior.

## Expected Behavior
Running the populate_fake command should populate SOLO with fake SDN data. 

## Observed Behavior
In settings.py using sqlite3 for unit tests causes Faker to error when creating the received_by coloumn. The terminal error reads`sqlite3.OperationalError: no such column: solo_rog_api_status.received_by`. Commenting out the lines in the screen shot below removed the errors. 

## Steps to Reproduce
To reproduce this issue…
1. run `docker-compose up —build`
2. run `docker-compose exec backend pip install -r requirements/requirements.dev.txt`
3. run `docker-compose exec backend python manage.py populate_fake`
4. check terminal

## Screenshots
![image](https://user-images.githubusercontent.com/59616370/78290064-25e61f00-74f1-11ea-96eb-f0376e7f0e2f.png)

**Comment by jhackshaw-dds** [comment]
@scottpiercewDDS I think this was closed via #299 - can you confirm and close if necessary?
