### ISSUE TITLE
Create CI/CD Pipeline Additions for Dependency Checking.

### ISSUE THREAD

**Issue by dds-hansolo** [deptofdefense/solo#35]
### Is your feature request related to a problem? Please describe.
The code quality must undergo rigorous testing to follow the guidelines outlined in the SSAG prior to deployment. Therefore, a basic pipeline should be outlined early to indicate the process of working with the CI/CD.

### Describe the solution you'd like
I would like an edited config.yml file which demonstrates how the CI/CD pipeline will check dependencies using Snyk via GithubActions or CircleCI.

### Describe alternatives you've considered
Check issue #16  for more info.

**Comment by jhackshaw-dds** [comment]
Implemented using SNYK for both front and backend dependency scanning.
