### ISSUE TITLE
Determine Container Orchestration and Scaling Implementation which can be portable from AWS to Azure

### ISSUE THREAD

**Issue by vcastro-DDS** [deptofdefense/solo#37]
## Research

Kubernetes implementations
1. Kops
2. Fargate
3. Kubespray
    a. Uses a .yaml file and integrates easily with terraform.
4. Conjure-up
    a. Can be deployed to both Amazon and Azure
    b. Requires a controller (additional VM to be deployed)
4. NetApps Kubernetes Service
    a. Cloud agnostic
    b. Can connect quickly and can be launched from Git
    c. Can be expensive (Since it is a third party orchestration

## Recommendation 
1. Sabers uses Fargate, so shall we.

## Action
Sabers Uses Fargate, so shall we.

## Screenshots
NA

**Comment by jhackshaw-dds** [comment]
GovCloud limitations requires ECS for initial deployment. Mon Cala team intends to migrate to Azure Kubernetes Service.
