### ISSUE TITLE
Parallelize CI/CD pipeline

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#40]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Parallelize CI/CD pipeline to speed up testing.

**Describe alternatives you've considered**
n/a

**Additional context**
Additional context can be found in issue #35

**Comment by dds-hansolo** [comment]
Workflows allow for backend and frontend tests to be run async.
