### ISSUE TITLE
Create Entity Relational Diagram (ERD) for Receipt of Goods

### ISSUE THREAD

**Issue by scottpiercewDDS** [deptofdefense/solo#49]
**Is your feature request related to a problem? Please describe.**
Needed to set up DB schema. 

**Describe the solution you'd like**
A third normal form ERD.

**Describe alternatives you've considered**

**Additional context**

**Comment by lit-dds** [comment]
Initial ERD v1
![solo_erd_v1](https://user-images.githubusercontent.com/59840583/76441891-7c4eba80-6396-11ea-8a12-1eaadd700f45.png)

**Comment by vcastro-DDS** [comment]
ERD exists, refer to diagram.
