### ISSUE TITLE
Establish SOLO domain name

### ISSUE THREAD

**Issue by jhackshaw-dds** [deptofdefense/solo#59]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
2 domain names provisioned in Route 53

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by vcastro-DDS** [comment]
We are using the following hostnames:
production= www.solo.code.mil
staging      = www.solo-stage.code.mil
dev            = www.solo-dev.code.mil
auth           = www.auth.solo.code.mil
