### ISSUE TITLE
Will MCCOG white list our IP if it is presenting a non-DoD certificate for HTTPS

### ISSUE THREAD

**Issue by jhackshaw-dds** [deptofdefense/solo#73]
## Research
Do we need multiple DoD server certificates for HTTPS and communication with GCSS, or a single one for GCSS communication.

## Recommendation 
_Provide a recommendation based upon the research._

## Action
_Describe the action taken._

## Screenshots
_Attach relevant screenshots here._

**Comment by vcastro-DDS** [comment]
Not necessary, we have a .mil domain.
