### ISSUE TITLE
Retrieve single SDN data

### ISSUE THREAD

**Issue by lit-dds** [deptofdefense/solo#94]
**Is your feature request related to a problem? Please describe.**
As an authenticated user, I want to retrieve data from a single SDN so that I can be informed about its status.

**Describe the solution you'd like**
This represents the python API needed to retrieve data from the API endpoint.

**Describe alternatives you've considered**

**Additional context**

**Comment by vcastro-DDS** [comment]
Completed through other issues loading GCSS-MC data into SOLO Status page.
